# Site settings
title: "Blog Clickstream"
email: "hernanxleguia@example.com"
description: "An√°lisis de clics en tiempo real con Apache Spark y Jekyll."
baseurl: "/blog-clickstream" # subdirectorio del repo en GitHub Pages
url: "https://hernanxleguia.github.io" # URL de tu usuario
twitter_username: "hernanxleguia"
github_username: "hernanxleguia"

# Theme
remote_theme: pages-themes/cayman@v0.2.0

# Plugins
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude unnecessary files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
